= Écriture collaborative
:toc:
:toc-title: Sommaire
:hide-uri-scheme:
:idprefix:
:icons: font
:revnumber: v1.1
:revdate: 6 avril 2017
:pdf-page-layout: landscape
//icons (in use in matrix.csv)
:checked: icon:check-square[]
:warning: icon:warning[]
:unchecked: icon:close[]

Dernière mise à jour du document (_{revnumber}_) : _{revdate}_.

== Contexte

L'association link:http://www.opendatafrance.net/[Open Data France] a contacté link:https://dtc-innovation.org[dtc innovation] pour prendre connaissance de l'état de l'art des *outils collaboratifs de rédaction de contenus*.

Pour le moment, leurs équipes fonctionnent avec plusieurs solutions, qui comportent chacune leurs avantages et leurs inconvénients. 
Les outils de collaboration comme _Google Docs_ sont jugés satisfaisants pour collaborer et gérer les permissions (collaboration, partage). Là où ils pêchent ? Le format de stockage et la réutilisation du contenu.

A l'inverse, _GitHub_ ou _GitBook_ sont jugés satisfaisants pour l'ubiquité du stockage et la versatilité des formats de contenus mais peu satisfaisants pour la collaboration (interfaces techniques, pertes de données, difficile de commenter).

Comment répondre à ces problèmes, fluidifier la chaîne de travail tout en préservant des environnements de collaboration faciles à prendre en main ? Comment créer une solution optimale pour exporter le contenu vers des formats divers ? 

== Objectifs

L'envie exprimée est de pouvoir *collaborer et distribuer de la documentation* avec plusieurs centaines de collectivités publiques de manière ouverte et transparente.

L'accent est mis sur la _réutilisation_ de plates-formes techniques existantes, leur _souplesse_ de mise en œuvre et de générer le _minimum de code spécifique_.

Idéalement, le *même ensemble d'outils permettra d'organiser des contenus _privés_, _publics_ et en _cours de rédaction_ de manière transparente*.
Les documents gérés par ces outils seront routés vers des destinations différentes (sites web, newsletters etc.) en fonction de leur étiquetage.

Si on résume les étapes, il s'agit de trouver un système optimal pour :
- archiver et organiser le contenu
- créer du contenu et l'ouvrir à de multiples collaborateurs (éditeur, correcteur, traducteur...)
- exporter le contenu souhaité et l'adapter selon son besoin (site, présentation, newsletter...)

== Des outils vers les données

Les interfaces de collaboration propriétaires ont une *tendance à enfermer les usagers* (_nous_) et *les contenus* (_nos efforts_) dans des interfaces et formats propriétaires.
Ces interfaces et formats nécessitent des efforts financiers supplémentaires pour rendre le contenu réutilisable.

Rares sont les outils dissociant le *processus de création du contenu* (modification de fichier) du *processus de revue* (contribution, suggestion).

Enfin, la sélection d'outils pour des raisons pratiques mène rapidement à leur *démultiplication*—et à la *difficulté de leur interopérabilité* de par l'enfermement des données dans des interfaces graphiques.

Rendre réutilisable une production de contenus passe par plusieurs choix :

Format de contenu::
Les formats textuels riches comme *Markdown* ou *Asciidoc* sont adaptés à la représentation du contenu textuel et illustré—document de travail privé et public, FAQ, support de formation, présentation, brouillon etc.
Ils peuvent être agrémentés de *métadonnées* servant lors de leur *transformation* dans un autre format de représentation comme _HTML_ ou _PDF_.
+
*HTML* est un format adapté à la *(re)présentation*.
Il peut être lui même transformé en _PDF_ ou agrémenté avec des librairies JavaScript comme link:https://github.com/hakimel/reveal.js/[reveal.js] ou link:https://github.com/bespokejs/bespoke[Bespoke] pour obtenir un équivalent de présentation _Powerpoint_ dans le navigateur—l'interopérabilité, la durabilité et l'ouverture en plus.

Interface de collaboration::
L'interface de collaboration offre une interface fonctionne d'*organisation* et des fonctionnalités d'*interaction* avec le contenu.
Cela vaut aussi bien pour les personnes à l'origine des contenus que celles proposant des modifications, ajouts, corrections ou traductions.
+
Ces outils offrent plusieurs fonctionnalités distinctes :

  Gestion du contenu;;
  Les contenus textuels, médias et autres fichiers peuvent être organisés selon des règles métier qui nous sont propres ;
  Workflow éditorial;;
  Un contenu ou suggestion de changement suit un chemin de validation avant d'être intégré au document de référence puis rendu public ;
  Changements en temps-réel;;
  Certaines interfaces permettent le travail à plusieurs sur un même document en simultané sans perte de données ;
  Permissions;;
  La *visibilité* d'un contenu ou d'une arborescence de contenus peut être déterminé à l'attention d'un public libre ou ciblé en fonction d'un profil d'actions (éditeur, correcteur etc.).

Accès au contenu::
Le contenu est mis à disposition dans le *format de référence de manière transparente*.
+
Cela garantit deux choses :

. une *indépendance* face à l'outil de l'interface de collaboration ;
. une *intégration* dans une chaine de publication—link:https://gitbook.com[GitBook], site web (type link:https://jekyllrb.com/[Jekyll]), synchronisation de fichiers (rsync, Dropbox etc.), newsletter etc.

Fichiers;;
Les contenus sont accessibles de manière interopérable sous forme de _fichiers_ en _lecture seule_, pour *archivage*, *transformation* et *republication*. +
L'historisation des contenus avec link:https://git-scm.com/[git] offre un canal d'accès en écriture pour des _power users_.

API;;
Les contenus sont accessibles de manière _programmatique_ via une interface HTTP. +
Des filtres de requêtes permettent de *dériver des documents publics* sur un ou plusieurs sites web—voire sous forme d'un jeu de données Open Data.

=== Temps-réel vs. collaboration

Il y a une distinction critique entre la modification de contenus en temps-réel et la collaboration.

La modification en temps-réel est impressionnante mais *tous les usagers modifient la même copie de travail*.

La collaboration permet d'*organiser les modifications et suggestions* de tous les usagers, y compris les personnes extérieures au groupe de travail.

Les outils poussant à la *collaboration* sont à privilégier car ils favorisent le *pilotage par la qualité du contenu*.

=== Scénario type

*Une seule interface web* permet de gérer *plusieurs collections* de contenus à différents stades de complétion :

* documents de référence ;
* base de connaissance ;
* supports de formation ;
* guides pratiques ;
* contenus périphériques présentation l'action.

Les collections de contenus sont organisés dans *un ou plusieurs entrepôts* au format *Markdown*.
Cela facilite le ciblage de leur publication : site(s) web, espace documentaire public, espace documentaire privé etc.

Les fichiers Markdown sont *transformés/dérivés en fichiers HTML* ou PDF lors de leur publication.

=== Solutions possibles

*Option A - Netlify CMS + Générateur de sites Jekyll + Synchronisation GitBook* +
+
*Netlify CMS* permet d'organiser des *collections* et des *workflows* de contenus entreposés au format *Markdown* dans des dépôts _privés_ et _publics_. +
+
Les contributions sont gérées comme suit :

* les *éditeurs créent et organisent* les contenus ;
* les contenus sont *publiés après validation* d'un éditeur ;
* les contributeurs connus soumettent des changements dans le CMS ;
* les contributeurs inconnus soumettent des changements depuis GitHub.
+
Les fichiers *Markdown* et les médias associés sont dérivés à l'aide de Jekyll pour être hébergés sur l'infrastructure de l'éditeur sous forme de documents HTML mis en forme avec CSS et JavaScript—ou encore sur link:https://pages.github.com/[GitHub Pages], link:https://docs.gitlab.com/ce/user/project/pages[GitLab Pages] ou link:https://www.gitbook.com/[GitBook], entres autres.
+
link:https://yhatt.github.io/marp/[Marp] est employé pour rédiger des présentations en Markdown, les versionner avec git et les exporter en PDF.
+
Toutes les les intégrations associées à *GitHub* s'intègrent à la chaine de publication—dont *GitBook*.

*Option B - Draft + Markdown + Générateur de sites Jekyll* +
+
*Draft* permet d'organiser des *collections* et des *contributions* de contenus entreposés au format *Markdown* dans des _Team Folders_.
+
Les documents peuvent être démarrés en brouillon dans *Evernote* ou *Google Docs* puis importés dans *Draft* afin de les synchroniser sur *Dropbox*.
+
*Dropbox* est installé sur l'infrastructure de l'éditeur pour synchroniser les fichiers *Markdown* et les médias associés. +
Le système reconstruit les sites *Jekyll* lors d'un changement.
+
*Draft* est employé pour rédiger des présentations en Markdown et les exporter en PDF.

<<<

== Outils et plate-formes

Les outils ayant nourri cette réflexion sont décrits de manière synthétique puis en détail.

Pour rappel, les solutions à privilégier entreposent le contenu dans un *format ouvert* type _Markdown_ ou _Asciidoc_, *gèrent les suggestions* et exposent les contenus sous *forme de fichiers*.

[format="csv", options="header",cols=">,7*^"]
|===
include::matrix.csv[]
|===

Légende::
  * {checked} supporté nativement
  * {warning} avec l'aide d'un plugin
  * {unchecked} pas supporté nativement

=== Contentful

icon:link[] https://www.contentful.com/

[horizontal]
Avantages::
  * Modèles de documents riches et sur mesure
  * Gestion des permissions
  * Contenus exposés comme des APIs Open Data
  * Mode hors ligne
  * Possibilité de générer des sites web basés sur une sélection de contenus

Inconvénients::
  * Payant (de gratuit—limité— jusque 3.000 à 12.000$ par an)

=== DokuWiki

icon:link[] https://www.dokuwiki.org/

[horizontal]
Avantages::
  * Wiki collaboratif
  * Gestion des permissions
  * Open Source
  * Stockage sous forme de fichiers
  * link:https://www.dokuwiki.org/plugin:gitbacked[Stockage sur GitHub]
  * Nombre d'utilisateurs illimités

Inconvénients::
  * Nécessite un hébergement
  * Pas de temps réel collaboratif

=== Draft

icon:link[] https://draftin.com/

[horizontal]
Avantages::
  * Format ouvert (Markdown)
  * Stockage sous forme de fichiers
  * Gestion des suggestions
  * Mode document, transcript et présentation
  * Synchronisation vers Dropbox et Evernote
  * Contenus exposés via API et Webhooks
  * Gestion des permissions

Inconvénients::
  * Pérennité du produit

=== Gollum

icon:link[] https://github.com/gollum/gollum

[horizontal]
Avantages::
  * Format ouvert (Markdown)
  * Open Source
  * Stockage sous forme de fichiers
  * Synchronise sur GitHub par défaut
  * Nombre d'utilisateurs illimités

Inconvénients::
  * Nécessite un hébergement (et le langage Ruby)
  * Pas de temps réel collaboratif

=== Google Docs

icon:link[] https://drive.google.com/

[horizontal]
Avantages::
  * Interface temps réel
  * Gestion des suggestions
  * Gestion fine des permissions
  * Fonctionne hors-ligne (uniquement dans Google Chrome)
  * Nombre d'utilisateurs illimités

Inconvénients::
  * Format propriétaire

=== HackMD

icon:link[] https://hackmd.io/

[horizontal]
Avantages::
  * Open Source
  * Interface temps réel
  * Mode document et présentation
  * Format ouvert (Markdown)

Inconvénients::
  * Pas d'organisation de fichiers/répertoires
  * Pérennité du produit
  * Pas de synchronisation vers Dropbox ou GitHub

=== MultiBàO

icon:link[] http://www.multibao.org/

[horizontal]
Avantages::
  * Arborescence libre
  * Gestion des suggestions
  * Open Source
  * Format ouvert (Markdown)
  * Synchronise sur GitHub par défaut
  * Nombre d'utilisateurs illimités (compte GitHub requis)

Inconvénients::
  * Acceptation de suggestions manuelle
  * Pas de temps réel collaboratif
  * Pas de gestion de permissions (public par défaut)

=== Netlify CMS

icon:link[] https://www.netlifycms.org/

[horizontal]
Avantages::
  * Format ouvert (Markdown)
  * Workflow éditorial
  * Synchronise sur GitHub, GitLab et BitBucket
  * Extensible via un système de widgets
  * Accès privilégié au support technique
  * Open Source

Inconvénients::
  * N/A

Alternatives::
  icon:link[] link:https://forestry.io/[forestry.io]
  icon:link[] link:https://www.siteleaf.com/[Siteleaf]

=== Notion

icon:link[] https://www.notion.so/

[horizontal]
Avantages::
  * Templates de pages
  * Éditeur visuel vraiment chouette
  * Gestion des permissions
  * Export en PDF/Markdown
  * Mode offline (macOS seulement)
  * Nombre d'utilisateurs illimités

Inconvénients::
  * Format propriétaire
  * Pas d'export automatique (juste manuel)
  * Gratuit jusqu'à 200 blocks de contenus—8$/utilisateur pour passer en illimité (ristournes potentielle pour les _non-profit_)

=== ProseMirror

icon:link[] http://prosemirror.net/

[horizontal]
Avantages::
  * Interface temps réel
  * Sauvegarde en Markdown
  * Open Source

Inconvénients::
  * Nécessite des développements spécifiques (gestion de l'authentification, export GitHub)
  * Nécessite un hébergement

=== Wikispaces

icon:link[] http://www.wikispaces.com/

[horizontal]
Avantages::
  * Interface temps réel
  * Gestion intégrée des suggestions
  * Gestion des permissions

Inconvénients::
  * Format propriétaire
  * Payant (de 100 à 400$ par an)
  * 2.000$ par an pour accéder à l'API

=== XWiki

icon:link[] http://www.xwiki.org/

[horizontal]
Avantages::
  * Multi-formes (Wiki, FAQ, blog, agenda, forums etc.)
  * Gestion des permissions
  * Exports multiples (HTML, LibreOffice, PDF)
  * Extensible via leur link:http://extensions.xwiki.org/xwiki/bin/view/Main/[annuaire d'extensions]
  * Synchronise sur GitHub via l'extension link:http://extensions.xwiki.org/xwiki/bin/view/Extension/XWiki%20Application%20-%20GitHub%20App[GitHub Commit Application]

Inconvénients::
  * Format propriétaire
  * Payant pour l'offre Cloud (6.000€ pour 100 utilisateurs, 9.000€ par an pour 250 utilisateurs)
  * Nécessite un hébergement pour la version gratuite

== Annexe

Le papier link:https://www.scientific.net/AMM.441.928[A Cloud-Based Real-Time Mobile Collaboration Wiki System] détaille un mécanisme idéal de collaboration en temps réel pour contenus textuels.

include::../footer-license.adoc[]
